version: '3'
services:
  web:
    restart: always
    build: .
    environment:
      - PORT=$PORT
      - HOST=0.0.0.0
      - VIRTUAL_HOST=$HOST
    # ports:
    #   - "$PORT:$PORT"
    expose:
      - $PORT
    command: poetry run python main.py
    volumes:
      - ./data:/app/data

    networks:
      - backend

networks:
  backend:
    external: true
