version: "3.8"
services:
  app:
    container_name: link_shortener
    restart: unless-stopped
    # image: ubuntu:22.04
    build: .
    command: bash -c "cd /app && chmod +x link_shortener && ./link_shortener"
    volumes:
      - ./data:/app/data
      - ./link_shortener:/app/link_shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.link_shortener.rule=Host(`link.paudel.me`)"
      - "traefik.http.routers.link_shortener.entrypoints=web,websecure"
      - "traefik.http.routers.link_shortener.tls.certresolver=le"

    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - proxy

networks:
  proxy:
    external: true

