version: '3'
services:
  web:
    restart: always
    build: .
    environment:
      - PORT=$PORT
      - HOST=0.0.0.0
    expose:
      - $PORT
    command: [ "/app/venv/bin/python", "main.py" ]
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.link_shortener.rule=Host("link.apaudel.com")
      - traefik.http.routers.link_shortener.entrypoints=websecure,web
      - traefik.http.routers.link_shortener.tls.certresolver=myresolver

networks:
  default:
    name: "backend"
