version: '3'
services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    expose:
      - $PORT
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.link_shortener.rule=Host("link.apaudel.com")
      - traefik.http.routers.link_shortener.entrypoints=websecure,web
      - traefik.http.routers.link_shortener.tls.certresolver=myresolver
    networks:
      - backend

networks:
  backend:
    external: true
